language: node_js
node_js:
  - '10'

env:
  - MOZ_HEADLESS=1

cache:
  yarn: true

addons:
  chrome: stable
  firefox: latest

before_install:
  - 'curl -o- -L https://yarnpkg.com/install.sh | bash -s --'
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --non-interactive

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - yarn test:ember $EMBER_TRY_SCENARIO --skip-cleanup

jobs:
  fail_fast: true

  include:
    - stage: Glimmer Tests
      name: Package Tests
      script: yarn test
    - name: Lint
      script: yarn lint
    - name: Type Lint
      script:
        - yarn build
        - yarn dtslint --installAll
        - yarn test:types

    - stage: Ember Tests
      env: EMBER_TRY_SCENARIO=ember-default
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4
